### ISSUE TITLE
Make configurable

### ISSUE THREAD

**Issue by kitt-cat** [Hack4Eugene/urban-pong-spectrum-2019#8]
Currently configuration is pretty much all hard coded; ideally we would load configuration from a config file and be able to set indicate which config file we want with an environment variable (which allows for managing separate dev/production configs, for example).  

First pass of things we'd want to be able to configure:
* Light output (emulator, serial, DMX controller)
* Geolocation/authentication requirement

**Comment by sfoster** [comment]
These 2 functions are now split into the raspberry pi light controller piece at https://github.com/gandalf3/colorlaunch, and the "spectrum" node.js app. The app development is tracked in this repo, where it reads in the config, but the config itself will get populated by the ansible deployment script, which is tracked in the https://github.com/sfoster/colorlaunch.net-config repo.
